import { FC } from 'react';

import { NextPage } from 'next';
import { Inter } from 'next/font/google';
import Head from 'next/head';
import { useRouter } from 'next/router';

import { CssBaseline, Typography } from '@mui/material';

import styled from '@emotion/styled';

import { Day001 } from '@/pages/001';
import { Day002 } from '@/pages/002';
import { Day004 } from '@/pages/004';
import { Day006 } from '@/pages/006';

const inter = Inter({ subsets: ['latin'] });

export const Tasks = styled.main`
  display: flex;
  justify-content: space-around;
  padding: 1rem;
  flex-wrap: wrap;

  div {
    cursor: pointer;
    text-align: center;
  }
`;

interface ItemProps {
  url: string;
  title: string;
  Component: FC;
}

const items: ItemProps[] = [
  { url: '/001', title: 'Day 001', Component: Day001 },
  { url: '/002', title: 'Day 002', Component: Day002 },
  { url: '/004', title: 'Day 004', Component: Day004 },
  { url: '/006', title: 'Day 006', Component: Day006 },
];

const Item: FC<ItemProps> = ({ url, title, Component }) => {
  const router = useRouter();

  return (
    <div onClick={(): void => void router.push(url)}>
      <Typography variant="overline">{title}</Typography>
      <Component />
    </div>
  );
};

const Home: NextPage = () => (
  <>
    <CssBaseline />
    <Head>
      <title>100 Days CSS Challenge</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <main className={inter.className}>
      <Typography variant="h2" textAlign="center">
        100 Days Challenge
      </Typography>
      <Tasks>
        {items.map((props) => (
          <Item key={props.url} {...props} />
        ))}
      </Tasks>
    </main>
  </>
);

export default Home;
