import { NextPage } from 'next';
import { Inter } from 'next/font/google';
import Head from 'next/head';

const inter = Inter({ subsets: ['latin'] });

const Home: NextPage = () => (
  <>
    <Head>
      <title>100 Days Challenge</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <main className={inter.className}>
      <h1>100 Days Challenge</h1>
    </main>
  </>
);

export default Home;
