import { NextPage } from 'next';
import { Inter } from 'next/font/google';
import Head from 'next/head';
import Link from 'next/link';

import { CssBaseline } from '@mui/material';

const inter = Inter({ subsets: ['latin'] });

const Home: NextPage = () => (
  <>
    <CssBaseline />
    <Head>
      <title>100 Days Challenge</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <main className={inter.className}>
      <h1>100 Days Challenge</h1>
      <ul>
        <li>
          <Link href="/001">Day 001</Link>
        </li>
        <li>
          <Link href="/002">Day 002</Link>
        </li>
      </ul>
    </main>
  </>
);

export default Home;
